scorecard:
  output: json
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/postgresql_v1alpha1_database_cr.yaml"
          - "deploy/crds/postgresql_v1alpha1_backup_cr.yaml"
        csv-path: "deploy/olm-catalog/postgresql-operator/0.1.0/postgresql-operator.v0.1.0.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/postgresql_v1alpha1_database_cr.yaml"
          - "deploy/crds/postgresql_v1alpha1_backup_cr.yaml"
        csv-path: "deploy/olm-catalog/postgresql-operator/0.1.0/postgresql-operator.v0.1.0.clusterserviceversion.yaml"
