##
# It is used to call the scorecard test/feature of the operatr-sdk tool
# Following the tests to use it:
# 1. Create the role_binding namespace ` kubectl create namespace postgresql-operator`
# 2. Run `operator-sdk scorecard`
##
scorecard:
  output: json
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/postgresql.dev4devs.com_databases_cr.yaml"
          - "deploy/crds/postgresql.dev4devs.com_backups_cr.yaml"
        csv-path: "deploy/olm-catalog/postgresql-operator/0.1.1/postgresql-operator.v0.1.1.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/postgresql.dev4devs.com_databases_cr.yaml"
          - "deploy/crds/postgresql.dev4devs.com_backups_cr.yaml"
        csv-path: "deploy/olm-catalog/postgresql-operator/0.1.1/postgresql-operator.v0.1.1.clusterserviceversion.yaml"
