# ---------------
# It is just used to test it in OLM before it be published
# ---------------
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: postgresql-operator
  namespace: marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/repository/dev4devs-com/postgresql-operator
  registryNamespace: dev4devs-com
