# ---------------
# It is just used to test it in OLM before it be published
# ---------------
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql-operatorsubsription
  namespace: marketplace
spec:
  channel: alpha
  name: postgresql-operator
  source: postgresql-operator
  sourceNamespace: marketplace